name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  bind:
    strategy:
      matrix:
        grammar:
          - "c"
          - "cpp"
          - "css"
          - "go"
          - "html"
          - "java"
          - "javascript"
          - "json"
          - "markdown"
          - "moonbit"
          - "ocaml"
          - "python"
          - "query"
          - "rust"
          - "swift"
          - "typescript"
          - "yaml"
      fail-fast: false
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Cache git
        uses: actions/cache@v4
        with:
          path: .git
          key: git-${{ github.sha }}

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup tree-sitter
        uses: tree-sitter/setup-action/cli@v2
        with:
          tree-sitter-ref: v0.25.4

      - name: Setup MoonBit
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Inspect MoonBit version
        run: |
          moon version --all
          moonrun --version

      - name: Update mooncakes.io index
        run: moon update

      - name: Get submodule commit SHA
        id: submodule-sha
        run: |
          grammar_path=src/grammars/tree-sitter-${{ matrix.grammar }}
          sha=$(git submodule status "$grammar_path" | awk '{print $1}')
          echo "sha=$sha" >> $GITHUB_OUTPUT

      - name: Cache bindings
        id: cache-bindings
        uses: actions/cache@v4
        with:
          path: src/languages
          key: tree-sitter-${{ matrix.grammar }}-${{ steps.submodule-sha.outputs.sha }}

      - name: Generate bindings
        if: steps.cache-bindings.outputs.cache-hit != 'true'
        run: python3 scripts/generate.py src/grammars/tree-sitter-${{ matrix.grammar }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: src/languages
          name: bindings-${{ matrix.grammar }}
          if-no-files-found: error

  test:
    needs: bind
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install MoonBit (Unix)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Install MoonBit (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Inspect MoonBit version
        run: |
          moon version --all
          moonrun --version

      - name: Update mooncakes.io index
        run: moon update

      - name: Setup MSVC
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: src/languages

      - name: Run tests
        run: |
          python3 scripts/test.py
